In [4]:
import numpy as np

In [5]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [13]:
# How many negative numbers are there?
a[a < 0]

array([-2, -1, -6, -7])

In [14]:
# How many positive numbers are there?
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [18]:
# How many even positive numbers are there?
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [19]:
# If you were to add 3 to each data point, how many positive numbers would there be?
b= a + 3
b[(b > 0) & (b % 2 == 0)]

array([26,  2,  6])

In [20]:
# If you squared each number, what would the new mean and standard deviation be?
b = (a ** 2).mean()
print(b)
c = (a ** 2).std()
print(c)

74.0
144.0243035046516


In [21]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.
b = a - a.mean()
b

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [22]:
#Calculate the z-score for each data point. Recall that the z-score is given by
b = (a - a.mean()) / a.std()
b

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py 
# and add your solutions.
part 1 coming soon